name: My first action

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say Hello
        run: |
          echo "Hello World! Hello!"
      - name: Now it is
        run: |
          date
      - name: Directory Content
        run: |
          ls -l
